import {t,setText} from '../docs/i18n.mjs';
import {expressionFrame,bossScenePose,speechDuration,keySpriteBacking,blackMatteSprite} from '../docs/animation.mjs';
import {CHAPTERS,NOTES,INFIRMARY,COURTYARD,saveEnvelope,validSave,PROLOGUE,portraitFor,CUTSCENES} from '../docs/campaign.mjs';
import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import {Game,MAP,WORLD,normalize,enemyLook} from '../docs/engine.mjs';
const root=new URL('../docs/',import.meta.url),html=fs.readFileSync(new URL('index.html',root),'utf8');const ids=new Set([...html.matchAll(/id="([^"]+)"/g)].map(m=>m[1]));let draws=0;
const context=new Proxy({getImageData(x,y,w,h){return {data:new Uint8ClampedArray(w*h*4)}},createRadialGradient(){return{addColorStop(){}}},drawImage(){draws++;}}, {get(o,k){return k in o?o[k]:(()=>{})},set(o,k,v){o[k]=v;return true;}});
function element(id){return{value:'',hidden:false,checked:true,disabled:false,children:[],style:{setProperty(){}},dataset:{},classList:{toggle(){}},getContext(){return context},getBoundingClientRect(){return{width:1000,height:625,left:0,top:0}},setPointerCapture(){},hasPointerCapture(){return false},releasePointerCapture(){},setAttribute(){},addEventListener(){},focus(){},append(b){this.children.push(b)},replaceChildren(){this.children=[]},querySelector(){return this.children.find(b=>!b.disabled)||element('child')},querySelectorAll(){return this.children},contains(){return false}};}
const els=Object.fromEntries([...ids].map(id=>[id,element(id)]));
let serverSave=null,serverRevision=0;
const sandbox={t,setText,initLanguages(){},saveRequest:(...args)=>sandbox.fetch(...args),expressionFrame,bossScenePose,speechDuration,keySpriteBacking,blackMatteSprite,CHAPTERS,NOTES,INFIRMARY,COURTYARD,saveEnvelope,validSave,PROLOGUE,portraitFor,CUTSCENES,enemyLook,structuredClone,setTimeout,Game,MAP,WORLD,normalize,console,Math,Set,Image:class{set src(s){assert(fs.existsSync(new URL(s,root)));queueMicrotask(()=>this.onload())}},ResizeObserver:class{observe(){}},document:{getElementById(id){if(id===undefined)return null;assert(ids.has(id),'missing element '+id);return els[id]},createElement:()=>element('button'),createElementNS:()=>element('svg'),querySelectorAll:()=>[],addEventListener(){}},window:{addEventListener(){}},matchMedia:()=>({matches:false}),requestAnimationFrame(){},fetch:async(p,options)=>{if(p==='/api/save'){if(options?.method==='PUT'){const body=JSON.parse(options.body);assert.equal(body.revision,serverRevision);serverSave=body.save;serverRevision++;}return{ok:true,json:async()=>({save:serverSave,revision:serverRevision})};}return{ok:true,json:async()=>JSON.parse(fs.readFileSync(new URL(p,root),'utf8'))};},location:{reload(){}}};
vm.createContext(sandbox);let src=fs.readFileSync(new URL('game.js',root),'utf8').replace(/^import .*;\n/gm,'');vm.runInContext(src,sandbox);await new Promise(r=>setTimeout(r,10));assert.equal(els.start.disabled,false);vm.runInContext("watchOpening();nextLine();",sandbox);assert.equal(els.speaker.textContent,'MS MIZUNO · SCHOOL PA');assert.equal(els['portrait-other'].src,'assets/portrait-teacher.webp');vm.runInContext('skipStory()',sandbox);assert.equal(vm.runInContext('mode',sandbox),'menu');assert.equal(serverRevision,0,'preview does not overwrite save');vm.runInContext('previewBossScene();nextLine();nextLine();tickCharacterAnimation(1);',sandbox);assert.equal(vm.runInContext('cinematic.id',sandbox),'bossIntro');assert.equal(vm.runInContext('game.power',sandbox),false);const at=vm.runInContext('animationTime',sandbox);vm.runInContext('togglePause();tickCharacterAnimation(2);',sandbox);assert.equal(vm.runInContext('animationTime',sandbox),at,'animation freezes while paused');vm.runInContext('togglePause();skipStory();',sandbox);assert.equal(vm.runInContext('mode',sandbox),'menu');assert.equal(serverRevision,0);vm.runInContext("start();nextLine();nextLine();",sandbox);assert.equal(els['portrait-other'].src,'assets/portrait-yui.webp');vm.runInContext("nextLine()",sandbox);assert.equal(els.speaker.textContent,'REINA');vm.runInContext("while(mode==='dialog')nextLine();",sandbox);assert.equal(vm.runInContext('mode',sandbox),'play');vm.runInContext("game.enemies=[];keys.add('d');frame(20);frame(40);",sandbox);assert(draws>0);vm.runInContext("game.player.x=points.panel.x;game.player.y=points.panel.y;interaction();",sandbox);assert.equal(vm.runInContext('mode',sandbox),'wires');vm.runInContext("togglePause();togglePause();",sandbox);assert.equal(vm.runInContext('mode',sandbox),'wires');vm.runInContext("chooseWire('left',0);chooseWire('right',1);",sandbox);assert.equal(vm.runInContext('connected.size',sandbox),0);
// Exercise pointer capture flow, wrong/outside drops and a valid release.
for(const [row,b]of els['right-terminals'].children.entries())b.getBoundingClientRect=()=>({left:850,top:30+row*100,right:950,bottom:90+row*100,width:100,height:60});
const pe=(x,y)=>({pointerId:7,button:0,clientX:x,clientY:y,preventDefault(){}});
sandbox.down=pe(100,60);sandbox.wrong=pe(900,60);sandbox.outside=pe(700,160);sandbox.correct=pe(900,160);
els['left-terminals'].children[0].onclick({detail:1});assert.equal(vm.runInContext('connected.size',sandbox),0,'mouse clicks do not connect');
vm.runInContext('beginWireDrag(down,0);moveWireDrag(wrong);endWireDrag(wrong);',sandbox);assert.equal(vm.runInContext('connected.size',sandbox),0,'wrong socket rejected');
vm.runInContext('beginWireDrag(down,0);moveWireDrag(outside);endWireDrag(outside);',sandbox);assert.equal(vm.runInContext('connected.size',sandbox),0,'outside release rejected');
vm.runInContext('beginWireDrag(down,0);moveWireDrag(correct);endWireDrag(correct);',sandbox);assert.equal(vm.runInContext('connected.size',sandbox),1,'matching drag release connects');assert.equal(vm.runInContext('wireDrag',sandbox),null);
vm.runInContext("for(let i=0;i<4;i++){chooseWire('left',i);chooseWire('right',i);}",sandbox);assert.equal(vm.runInContext('game.power',sandbox),true);assert.equal(vm.runInContext('mode',sandbox),'dialog');vm.runInContext('nextLine();nextLine();',sandbox);assert.equal(vm.runInContext('mode',sandbox),'play');vm.runInContext('game.enemies=[];game.player.x=points.exit.x;game.player.y=points.exit.y;interaction();',sandbox);assert.equal(vm.runInContext('cinematic.id',sandbox),'infirmary');assert.equal(vm.runInContext('chapter',sandbox),0);vm.runInContext('togglePause();',sandbox);assert.equal(els.restart.disabled,true);const elapsed=vm.runInContext('shotElapsed',sandbox);vm.runInContext('tickCutscene(10);togglePause();',sandbox);assert.equal(vm.runInContext('shotElapsed',sandbox),elapsed);vm.runInContext('skipStory();game.enemies=[];',sandbox);assert.equal(vm.runInContext('chapter',sandbox),1);assert.equal(vm.runInContext('mode',sandbox),'play');
vm.runInContext('game.player.x=INFIRMARY.items[0].x;game.player.y=INFIRMARY.items[0].y;interaction();nextLine();',sandbox);assert(vm.runInContext('game.flags.medicine',sandbox));
vm.runInContext('game.player.x=INFIRMARY.items[1].x;game.player.y=INFIRMARY.items[1].y;interaction();nextLine();',sandbox);assert(vm.runInContext('notes.has("card")',sandbox));
vm.runInContext('game.player.x=points.panel.x;game.player.y=points.panel.y;interaction();chooseRelay(1);',sandbox);assert.equal(vm.runInContext('relayInput.length',sandbox),0);
vm.runInContext('for(const n of [3,1,4,2])chooseRelay(n);nextLine();nextLine();',sandbox);assert(vm.runInContext('game.power',sandbox));
vm.runInContext('game.enemies=[];game.player.x=points.exit.x;game.player.y=points.exit.y;interaction();',sandbox);assert.equal(vm.runInContext('mode',sandbox),'hiding');
vm.runInContext('tickHiding(6);chooseHidingSpot(0);tickHiding(1.5);tapHeartbeat();',sandbox);assert.equal(vm.runInContext('hiding.panic',sandbox),56,'early tap raises panic');assert.equal(vm.runInContext('hiding.phase',sandbox),'rhythm','one mistake is recoverable');
vm.runInContext('tickHiding(.2);tapHeartbeat();tickHiding(.2);tapHeartbeat();',sandbox);assert.equal(vm.runInContext('hiding.phase',sandbox),'caught','panic overload reveals Reina');
vm.runInContext('startHiding(hiding.done);tickHiding(6);chooseHidingSpot(0);togglePause();tickHiding(10);',sandbox);assert.equal(vm.runInContext('hiding.time',sandbox),0,'pause freezes heartbeat');vm.runInContext('togglePause();tickHiding(3);',sandbox);assert.equal(vm.runInContext('hiding.panic',sandbox),62,'missed beat raises panic');
vm.runInContext('tickHiding(hiding.next-hiding.time);tapHeartbeat();',sandbox);assert.equal(vm.runInContext('hiding.panic',sandbox),49,'correct beat reduces panic');
vm.runInContext('startHiding(hiding.done);tickHiding(6);for(let r=0;r<3;r++){chooseHidingSpot(r);for(let b=0;b<6;b++){tickHiding(hiding.next-hiding.time);tapHeartbeat();}tickHiding(4);}tickHiding(4);',sandbox);assert.equal(vm.runInContext('game.flags.hideSurvived',sandbox),true);assert.equal(vm.runInContext('cinematic.id',sandbox),'courtyard');vm.runInContext('while(cinematic)tickCutscene(30);',sandbox);assert.equal(vm.runInContext('chapter',sandbox),2);
vm.runInContext('game.enemies=[];game.player.x=points.panel.x;game.player.y=points.panel.y;interaction();',sandbox);assert.equal(vm.runInContext('cinematic.id',sandbox),'bossIntro');assert.equal(vm.runInContext('game.power',sandbox),false);vm.runInContext('skipStory()',sandbox);assert(vm.runInContext('game.enemies.some(e=>e.kind==="boss")',sandbox));
vm.runInContext("game.enemies.find(e=>e.kind==='boss').hp=0;game.emit('kill',{kind:'boss',id:100});handleEvents();",sandbox);assert.equal(vm.runInContext('cinematic.id',sandbox),'bossDown');vm.runInContext('skipStory()',sandbox);assert(vm.runInContext('game.flags.bossDefeatSeen',sandbox));
vm.runInContext('game.enemies=[];game.charge=30;game.player.x=points.exit.x;game.player.y=points.exit.y;interaction();nextLine();nextLine();nextLine();',sandbox);assert.equal(vm.runInContext('mode',sandbox),'victory');
await new Promise(r=>setTimeout(r,10));assert(serverSave.completed);assert(validSave(serverSave));vm.runInContext('continueGame()',sandbox);assert.equal(vm.runInContext('mode',sandbox),'victory');assert.equal(els['ending-evidence'].textContent,'The responders secure the school and begin investigating the chemical exposure.');

console.log('PASS: startup assets/IDs, opening, canvas draw calls, wire puzzle mismatch/match, modal pause, chapter transitions, trauma kit, relay puzzle, boss spawning, final gate, cloud-save queue and restored ending. Mock DOM test; not browser QA.');
